# Generated by Django 4.0.1 on 2022-11-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_rename_bookedby_car_bookedby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bookedCar',
            new_name='carBooked',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
